### ISSUE TITLE
MagicLib depency mistake

### ISSUE THREAD

**Issue by sternschnaube** [Crystal0404/CrystalCarpetAddition#1]
I was using the version specific for 1.20.2 "magiclib-1.20.2-0.7.398+fe2125a-stable".

Mod was showing an error that MagicLib isn't present - "magiclib-all-0.7.398+fe2125a-stable" worked instead, this should be fixed for the future.

**Comment by Crystal0404** [comment]
This may not be a bug,  Please check https://github.com/Hendrix-Shen/MagicLib/issues/7

If you use ```CrystalCarpetAddition-all-v0.1.1.jar```, you must use ```magiclib-all-0.7.398+fe2125a-stable.jar```

**Comment by sternschnaube** [comment]
Please be more flexible with the depency need. Not everyone is using the packed version with many Minecraft versions. And this should not be forced to the user in the end. That's it.

**Comment by sternschnaube** [comment]
I was looking into the fabric-mod.json from your mod and TweakMyClient as example. I didn't get more clever.
Weird behaviour like I never had before.

**Comment by Crystal0404** [comment]
MagicLib is in the early development stage，May receive support in the future.

**Comment by Crystal0404** [comment]
In fact, you should have initiated this issue in the MagicLib project.  QVQ

**Comment by sternschnaube** [comment]
If Hendrix would just publish the bundled version or for specific versions, this would not happen.

I'm just worried if someone should encounter this problem, they might be confused 😂

**Comment by sternschnaube** [comment]
> In fact, you should have initiated this issue in the MagicLib project.  QVQ

I thought first this problem lays here and with the configured depency, since I never had this problem with other mods based on MagicLib.
