### ISSUE TITLE
恳请作者把海豚复制重新引入

### ISSUE THREAD

**Issue by torresmamon** [Crystal0404/CrystalCarpetAddition#10]
### Motivation

海豚复制在1.16.5之后的版本被修复，恳请作者能重新引入

### Description

海豚复制在1.16.5之后的版本被修复，恳请作者能重新引入

**Comment by Crystal0404** [comment]
我想了一下还是不打算把这个功能加入CCA...我不喜欢这个bug, 并且有其它方法可以替代海豚复制
