### ISSUE TITLE
1.21恢复旧版本袭击导致袭击静态迁移失效，何为氕氘氚的静态迁移袭击塔失效

### ISSUE THREAD

**Issue by vocaloidkiss** [Crystal0404/CrystalCarpetAddition#13]
### Bug description

1.21恢复旧版本袭击导致袭击静态迁移失效，何为氕氘氚的静态迁移袭击塔失效

### Steps to reproduce

1.21恢复旧版本袭击导致袭击静态迁移失效，何为氕氘氚的静态迁移袭击塔失效

### Minecraft version

1.21

### CrystalCarpetAddition version

1.9.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.
- [X] I confirm that there is no mention of the issue in the documentation.

**Comment by Crystal0404** [comment]
请附上袭击塔出处, 需要进行一些测试

**Comment by vocaloidkiss** [comment]
【「古城之中」900,000 物品/小时 | 幽匿袭击农场】 https://www.bilibili.com/video/BV19E421u7BQ/?share_source=copy_web&vd_source=daf7f26f745024a6f0c42698c598de03


【「极致性能」900,000 物品/小时 | 堆叠袭击农场V7】 https://www.bilibili.com/video/BV1bz4y1M7zM/?share_source=copy_web&vd_source=daf7f26f745024a6f0c42698c598de03

**Comment by vocaloidkiss** [comment]
附存档投影使用手册
[900k 幽匿袭击农场 作者：何为氕氘氚.zip](https://github.com/user-attachments/files/17449977/900k.zip)

**Comment by vocaloidkiss** [comment]
袭击会在第一波生成后胜利，并无法迁移

**Comment by Crystal0404** [comment]
无法复现, 两台袭击塔在开启`ReIntroduceOldVersionRaid`规则后均正常工作

环境:
```
	- carpet 1.4.147+v240613
	- carpet-tis-addition 1.63.2
	   \-- conditional-mixin 0.6.3
	- cca 1.9.0
	   |-- conditional-mixin 0.6.3
	   \-- mixinextras 0.4.1
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- java 21
	- lithium 0.13.1
	- minecraft 1.21
	- sodium 0.6.0-beta.2+mc1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   \-- fabric-resource-loader-v0 1.3.0+5659912919
```

请尝试仅保留cca相关mod测试.

**Comment by Crystal0404** [comment]
关闭, 无法复现所述问题.

如果能给出详细的复现步骤, 请再重新打开

**Comment by vocaloidkiss** [comment]
@Crystal0404 发现问题所在，是由于TISaddition的fakeplayerticklikereal导致的微时序问题。关闭无误
