### ISSUE TITLE
更新带有CCAProtocol的1.20.1的CrystalCarpetAddition

### ISSUE THREAD

**Issue by Young912** [Crystal0404/CrystalCarpetAddition#2]
您好，我需要一份带有CCAProtocol的1.20.1的CrystalCarpetAddition，模组很棒，希望您能帮忙，谢谢！

**Comment by Crystal0404** [comment]
> 您好，我需要一份带有CCAProtocol的1.20.1的CrystalCarpetAddition，模组很棒，希望您能帮忙，谢谢！
[CCA.zip](https://github.com/Crystal0404/CrystalCarpetAddition/files/14060945/CCA.zip)

我修改了一下注册文件, 它可以在1.20.1使用，放心, 它只是名字不正确。
但是CCAProtocol在Velocity、BungeeCord等群组服环境下不能正常工作, 你只能在普通的Fabric服务器上使用它
