### ISSUE TITLE
1.20.1服务器珍珠炮 末影珍珠不能自加载

### ISSUE THREAD

**Issue by wj-lxax** [Crystal0404/CrystalCarpetAddition#5]

**Comment by Crystal0404** [comment]
请使用问题模板Bug Report重新开启一个issues, 此issues描述所提供信息太少, 我无法准确定位问题

**Comment by wj-lxax** [comment]
问题:服务器珍珠炮开炮之后 珍珠不能自加载
版本:1.20.1 
    Fabric服务器
    
    服务端:fabric-api-0.89.0+1.20.1.jar
          [地毯]fabric-carpet-1.20-1.4.112+v230608.jar
          
    客户端:fabric-api-0.91.0+1.20.1.jar
          fabric-carpet-1.20-1.4.112+v230608.jar
 
cca客户端和服务端均已添加 1.2.0版本       

具体情况:
在客户端 末影珍珠炸出去后 能被拦截 并传送.
在服务器 珍珠炸出去后 能拦截 但并不能传送。要往拦截点飞，加载到珍珠之后，才会被传送。

补充:
客户端和服务器都是同一存档 拦截位置相同 只存在本mod(并无其他珍珠自加载的mod或指令)
本mod指令只开启珍珠加载  
在此前我也试了其他的珍珠自加载mod 都是客户端行 但服务器不行.

**Comment by wj-lxax** [comment]
也有可能是其他mod的问题，我再去测试测试

**Comment by Crystal0404** [comment]
据Carpet-extras那边的报告, 珍珠加载需要预先加载过沿途经过的区块才能正常工作.

你可以开启tis-carpet的`/log ticket ender_pearl`来帮助测试

**Comment by Crystal0404** [comment]
我锁定了这个issues，如果有新的进展, 请使用问题模板->Bug Report 重新开启一个issues
