### ISSUE TITLE
服务器珍珠自加载问题

### ISSUE THREAD

**Issue by wj-lxax** [Crystal0404/CrystalCarpetAddition#6]
### Bug description

服务器珍珠炮开炮之后 珍珠不能自加载

### Steps to reproduce

1.发射珍珠
2.珍珠被炸飞
3.玩家并没被传送

### Expected behavior

拦截点拦截珍珠 玩家传送

### Actual behavior

玩家并没有被传送 

### Minecraft version

1.20.1 

### CrystalCarpetAddition version

1.2.0

### Other information

玩家只有飞到拦截点附近加载到珍珠之后，才会被传送

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by wj-lxax** [comment]
破案了 
我在最开始测试时，服务端有其他mod
之后服务端我只留了
fabric-api-0.89.0+1.20.1.jar
[地毯]fabric-carpet-1.20-1.4.112+v230608.jar
CrystalCarpetAddition-mc1.20.1-v1.2.0.jar
再进行测试，发现珍珠可以自加载

我开始对其他mod进行排查。终于发现是servercore的问题
删掉之后珍珠可以自加载了。

此外我还进行了测试。1.20.1 servercore有4个版本，依次添加之后，发现全都不能进行加载

**Comment by Crystal0404** [comment]
servercore取缔了原版的投掷物相关方法, 因此mixin到原版方法珍珠加载无法生效

不过看servercore介绍, 貌似可以单独禁用有关优化. 不过我更推荐使用[锂](https://modrinth.com/mod/lithium)来对mc进行优化

**Comment by wj-lxax** [comment]
![a0383ef7b8c0e242ae3e91ecb9eef039](https://github.com/Crystal0404/CrystalCarpetAddition/assets/101759265/5509eb57-8aa5-401e-acd2-b415158c3f0a)
用ai解决的。把配置文件中reduce_sync_loads设置成false 其余没动，就可以了

servercore-fabric-1.3.9+1.20.1.jar
配置文件位置:/config/servercore.toml
