### ISSUE TITLE
回来吧我的堆叠附魔书

### ISSUE THREAD

**Issue by ailixiyaX** [Crystal0404/CrystalCarpetAddition#7]
### Motivation

高版本堆叠附魔书被修复 希望加回来

### Description

高版本堆叠附魔书被修复 希望加回来

**Comment by Crystal0404** [comment]
我有空会看看这个

**Comment by Crystal0404** [comment]
我破开了砂轮的限制, 但是附魔书最多只能堆叠两本
![2024-05-03_21 31 41](https://github.com/Crystal0404/CrystalCarpetAddition/assets/120556221/ab3556d2-08fa-48ad-a268-0e6efe34e96b)
理论上可以继续堆叠, 但是因为mojang重写了很多代码, 导致堆叠附魔书离开玩家背包到其它地方就会立刻散开, 比如我现在放入漏斗, 就会立刻散开成两本
![2024-05-03_21 34 30](https://github.com/Crystal0404/CrystalCarpetAddition/assets/120556221/eda85776-d3cb-489d-bf84-19f52450d56b)
当然砂轮也是, 在我尝试把堆叠的附魔书继续堆叠时, 就会直接散开, 也就不能进一步堆叠.

相关交互相关代码经过mojang多年的积累，到了一个十分恐怖的地步, 我实在不想去研究它们.这个功能超出了我的能力, 可以尝试去tis-carpet那里提出增强建议，看看fallen有没有办法

**Comment by ailixiyaX** [comment]
emm 好的 麻烦了
